## with NumPy

In [6]:
from numpy import array, zeros
a=array([[3,-2,5,0],
         [4,5,8,1],
         [1,1,2,1],
         [2,7,6,5]], float)
b=array([2,4,5,7],float)
n=len(b)
x=zeros(n,float)
for k in range(n-1):
  for i in range(k+1,n):
    if a[i,k]==0:
      continue
    factor=a[k,k]/a[i,k]
    for j in range(k,n):
      a[i,j]=a[k,j]-a[j,j]*factor
    b[i]=b[k]-b[i]*factor
print(a)

print(b)

x[n-1]=b[n-1]/a[n-1,n-1]
for i in range(n-2,-1,-1):
    sum_ax=0
    for j in range(i+1,n):
        sum_ax += a[i,j]*x[j]
    x[i]=(b[i]-sum_ax)/a[i,i]
print('result:',x)    

[[  3.          -2.           5.           0.        ]
 [  0.75        -5.75         3.5         -3.75      ]
 [ -6.          -7.91803279   3.12295082  -6.57786885]
 [ -1.5        -10.74056604   1.55257091  -1.41889906]]
[ 2.         -1.         -5.90163934 -1.68907366]
result: [-0.51367314 -0.22651248  0.61759889  1.19041143]


In [25]:
import sympy
import gauss

def main():
    A = sympy.Matrix([[3, 4, 5], [1, -1, -2], [2, 1, 2], [3, -3, 1], [1, 2, 2]])
    b = sympy.Matrix([7, 0, 3, 0, 5])
    print("Исходная матрица A:")
    sympy.print(A)
    print("\nВектор b:")
    sympy.print(b)
    x = gauss.gauss(A, b)
    if x:
        print("\nРезультат:", x)

if __name__ == "__main__":
    main()

OSError: [WinError 193] %1 не является приложением Win32

# Solving a tridiagonal matrix

In [14]:
import math
 
a = [[ 10.8000, 0.0475,      0, 0     ],
     [  0.0321, 9.9000, 0.0523, 0     ],
     [       0, 0.0369, 9.0000, 0.0570],
     [       0,      0, 0.0416, 8.1000]]
 
b = [12.1430, 13.0897, 13.6744, 13.8972]
 

def isCorrectArray(a):
    n = len(a)
    
    for row in range(0, n):
        if( len(a[row]) != n ):
            print('Не соответствует размерность')
            return False
        
    for row in range(1, n - 1):
        if(abs(a[row][row]) < abs(a[row][row - 1]) + abs(a[row][row + 1])):
            print('Не выполнены условия достаточности')
            return False
 
    if (abs(a[0][0]) < abs(a[0][1]))or(abs(a[n - 1][n - 1]) < abs(a[n - 1][n - 2])):
        print('Не выполнены условия достаточности')
        return False
        
    
    for row in range(0, len(a)):
        if( a[row][row] == 0 ):
            print('Нулевые элементы на главной диагонали')
            return False
    return True
 
def solution(a, b):
    if( not isCorrectArray(a) ):
        print('Ошибка в исходных данных')
        return -1 
 
    n = len(a)

    # Прямой ход
    v = [0 for k in range(0, n)]
    u = [0 for k in range(0, n)]
    # для первой 0-й строки
    v[0] = a[0][1] / (-a[0][0]) 
    u[0] = ( - b[0]) / (-a[0][0]) 
    for i in range(1, n - 1): # заполняем за исключением 1-й и (n-1)-й строк матрицы
        v[i] = a[i][i+1] / ( -a[i][i] - a[i][i-1]*v[i-1] )
        u[i] = ( a[i][i-1]*u[i-1] - b[i] ) / ( -a[i][i] - a[i][i-1]*v[i-1] )
    # для последней (n-1)-й строки
    v[n-1] = 0
    u[n-1] = (a[n-1][n-2]*u[n-2] - b[n-1]) / (-a[n-1][n-1] - a[n-1][n-2]*v[n-2])

    # Обратный ход
    x[n-1] = u[n-1]
    for i in range(n-1, 0, -1):
        x[i-1] = v[i-1] * x[i] + u[i-1]
        
    return x    
            
x = solution(a, b)  
print_arr('Решение: ','x', x)

Решение: 
x[0] =   1.1186
x[1] =   1.3106
x[2] =   1.5032
x[3] =   1.7080
